"""Direct Linux joystick input for dArkOS R36S controls."""

import fcntl
import os
import struct
from collections import deque
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from time import monotonic


class InputAction(Enum):
    """Logical actions understood by the terminal UI."""

    UP = "up"
    DOWN = "down"
    LEFT = "left"
    RIGHT = "right"
    SELECT = "select"
    BACK = "back"
    BACKSPACE = "backspace"
    SUBMIT_SEARCH = "submit_search"
    PAGE_UP = "page_up"
    PAGE_DOWN = "page_down"
    START = "start"


JS_EVENT_BUTTON = 0x01
JS_EVENT_AXIS = 0x02
JS_EVENT_INIT = 0x80
AXIS_THRESHOLD = 16_000
EVENT_STRUCT = struct.Struct("IhBB")
REPEAT_DELAY_SECONDS = 0.35
REPEAT_INTERVAL_SECONDS = 0.08
REPEAT_ACTIONS = frozenset((InputAction.UP, InputAction.DOWN))

# Semantic Linux input-event codes returned for joydev button indexes.
KEY_UP = 103
KEY_LEFT = 105
KEY_RIGHT = 106
KEY_DOWN = 108
BTN_SOUTH = 0x130
BTN_EAST = 0x131
BTN_NORTH = 0x133
BTN_WEST = 0x134
BTN_TL = 0x136
BTN_TR = 0x137
BTN_SELECT = 0x13A
BTN_START = 0x13B
BTN_DPAD_UP = 0x220
BTN_DPAD_DOWN = 0x221
BTN_DPAD_LEFT = 0x222
BTN_DPAD_RIGHT = 0x223

# Values generated by Linux's _IOR macro for linux/joystick.h.
JSIOCGBUTTONS = 0x80016A12
JSIOCGBTNMAP = 0x84006A34
BUTTON_MAP_BYTES = 1024
GAMEPAD_LOG_ENV = "DW_GAMEPAD_LOG"

BUTTON_CODE_ACTIONS: dict[int, InputAction] = {
    KEY_UP: InputAction.UP,
    KEY_DOWN: InputAction.DOWN,
    KEY_LEFT: InputAction.LEFT,
    KEY_RIGHT: InputAction.RIGHT,
    BTN_SOUTH: InputAction.BACK,
    BTN_EAST: InputAction.SELECT,
    BTN_NORTH: InputAction.BACKSPACE,
    BTN_WEST: InputAction.SUBMIT_SEARCH,
    BTN_TL: InputAction.PAGE_UP,
    BTN_TR: InputAction.PAGE_DOWN,
    BTN_SELECT: InputAction.BACK,
    BTN_START: InputAction.START,
    BTN_DPAD_UP: InputAction.UP,
    BTN_DPAD_DOWN: InputAction.DOWN,
    BTN_DPAD_LEFT: InputAction.LEFT,
    BTN_DPAD_RIGHT: InputAction.RIGHT,
}

BUTTON_ACTIONS: dict[int, InputAction] = {
    0: InputAction.BACK,
    1: InputAction.SELECT,
    2: InputAction.BACKSPACE,
    3: InputAction.SUBMIT_SEARCH,
    4: InputAction.PAGE_UP,
    5: InputAction.PAGE_DOWN,
    # The R36S exists with two common dArkOS/ArkOS controller layouts.  Keep
    # both Select/Start pairs so the native joydev reader works on either DTB.
    6: InputAction.BACK,
    7: InputAction.START,
    8: InputAction.BACK,
    9: InputAction.START,
}
STANDARD_DPAD_BUTTONS: dict[int, InputAction] = {
    11: InputAction.UP,
    12: InputAction.DOWN,
    13: InputAction.LEFT,
    14: InputAction.RIGHT,
}
R36S_DPAD_BUTTONS: dict[int, InputAction] = {
    14: InputAction.UP,
    15: InputAction.DOWN,
    16: InputAction.LEFT,
    17: InputAction.RIGHT,
}
# Linux joydev commonly exposes X/Y on 0/1, Z or RX on 2/3, RY on 4, and the
# D-pad hat on 6/7. This also covers dArkOS device-tree variants where the right
# stick is reported as RX/RY rather than the older Z/RX pairing.
HORIZONTAL_AXES = {0, 2, 6}
VERTICAL_AXES = {1, 3, 4, 7}


@dataclass(slots=True)
class LinuxJoystick:
    """Non-blocking reader for Linux's stable ``/dev/input/js*`` interface."""

    path: Path
    _file_descriptor: int
    _axis_state: dict[int, int] = field(default_factory=dict)
    _pending: deque[InputAction] = field(default_factory=deque)
    _repeat_action: InputAction | None = None
    _repeat_due_at: float = 0.0
    _highest_initialized_button: int = -1
    _button_codes: tuple[int, ...] = ()

    @classmethod
    def open_first(cls, input_directory: Path = Path("/dev/input")) -> LinuxJoystick | None:
        """Open the first readable joystick, normally the R36S built-in controls."""

        for path in sorted(input_directory.glob("js*")):
            try:
                descriptor = os.open(path, os.O_RDONLY | os.O_NONBLOCK)
            except OSError:
                continue
            button_codes = cls._read_button_codes(descriptor)
            mapping = ", ".join(f"{index}={code}" for index, code in enumerate(button_codes))
            _write_diagnostic(f"gamepad map {path}: {mapping or 'unavailable'}")
            return cls(
                path=path,
                _file_descriptor=descriptor,
                _button_codes=button_codes,
            )
        return None

    @staticmethod
    def _read_button_codes(descriptor: int) -> tuple[int, ...]:
        """Read semantic Linux key codes for every joydev button index."""

        try:
            count_buffer = bytearray(1)
            fcntl.ioctl(descriptor, JSIOCGBUTTONS, count_buffer, True)
            count = count_buffer[0]
            mapping_buffer = bytearray(BUTTON_MAP_BYTES)
            fcntl.ioctl(descriptor, JSIOCGBTNMAP, mapping_buffer, True)
        except OSError as error:
            _write_diagnostic(f"gamepad semantic map unavailable: {error}")
            return ()
        return struct.unpack_from(f"={count}H", mapping_buffer)

    def poll(self) -> InputAction | None:
        """Return the next available action without blocking the TUI."""

        if self._pending:
            return self._pending.popleft()
        try:
            payload = os.read(self._file_descriptor, EVENT_STRUCT.size * 16)
        except BlockingIOError:
            return self._poll_repeat()
        except OSError:
            self.close()
            return None

        for offset in range(0, len(payload) - EVENT_STRUCT.size + 1, EVENT_STRUCT.size):
            _timestamp, value, event_type, number = EVENT_STRUCT.unpack_from(payload, offset)
            action = self.decode_event(value, event_type, number)
            if action is not None:
                self._pending.append(action)
        return self._pending.popleft() if self._pending else self._poll_repeat()

    def decode_event(self, value: int, event_type: int, number: int) -> InputAction | None:
        """Translate one js event; public to allow device-independent tests."""

        kind = event_type & ~JS_EVENT_INIT
        if event_type & JS_EVENT_INIT:
            if kind == JS_EVENT_BUTTON:
                self._highest_initialized_button = max(self._highest_initialized_button, number)
            return None
        if kind == JS_EVENT_BUTTON:
            action = self._button_action(number)
            if value:
                code = self._button_codes[number] if number < len(self._button_codes) else None
                label = action.value if action is not None else "ignored"
                _write_diagnostic(f"gamepad button index={number} code={code} action={label}")
            if action not in REPEAT_ACTIONS:
                return action if value else None
            if value:
                self._start_repeat(action)
                return action
            self._stop_repeat(action)
            return None
        if kind != JS_EVENT_AXIS:
            return None

        direction = -1 if value < -AXIS_THRESHOLD else 1 if value > AXIS_THRESHOLD else 0
        previous = self._axis_state.get(number, 0)
        self._axis_state[number] = direction
        previous_action = self._axis_action(number, previous)
        if direction == 0:
            self._stop_repeat(previous_action)
            return None
        if direction == previous:
            return None
        action = self._axis_action(number, direction)
        self._stop_repeat(previous_action)
        if action in REPEAT_ACTIONS:
            self._start_repeat(action)
        return action

    def _button_action(self, number: int) -> InputAction | None:
        if number < len(self._button_codes):
            code_action = BUTTON_CODE_ACTIONS.get(self._button_codes[number])
            if code_action is not None:
                return code_action
        action = BUTTON_ACTIONS.get(number)
        if action is not None:
            return action
        dpad = (
            R36S_DPAD_BUTTONS
            if self._highest_initialized_button < 11 or self._highest_initialized_button > 14
            else STANDARD_DPAD_BUTTONS
        )
        return dpad.get(number)

    @staticmethod
    def _axis_action(number: int, direction: int) -> InputAction | None:
        if not direction:
            return None
        if number in HORIZONTAL_AXES:
            return InputAction.LEFT if direction < 0 else InputAction.RIGHT
        if number in VERTICAL_AXES:
            return InputAction.UP if direction < 0 else InputAction.DOWN
        return None

    def _start_repeat(self, action: InputAction) -> None:
        self._repeat_action = action
        self._repeat_due_at = monotonic() + REPEAT_DELAY_SECONDS

    def _stop_repeat(self, action: InputAction | None) -> None:
        if action is not None and action == self._repeat_action:
            self._repeat_action = None
            self._repeat_due_at = 0.0

    def _poll_repeat(self) -> InputAction | None:
        if self._repeat_action is None or monotonic() < self._repeat_due_at:
            return None
        self._repeat_due_at = monotonic() + REPEAT_INTERVAL_SECONDS
        return self._repeat_action

    def close(self) -> None:
        """Release the device descriptor, tolerating repeated calls."""

        if self._file_descriptor < 0:
            return
        try:
            os.close(self._file_descriptor)
        finally:
            self._file_descriptor = -1


def _write_diagnostic(message: str) -> None:
    """Append controller diagnostics when the device launcher supplies a log path."""

    log_value = os.environ.get(GAMEPAD_LOG_ENV)
    if not log_value:
        return
    try:
        with Path(log_value).open("a", encoding="utf-8") as stream:
            stream.write(message + "\n")
    except OSError:
        pass
